"""Contract tests for v0.5.0 client communicating with v1.0.0 server.

These tests verify that a client using v0.5.0 protocol (with security features)
can successfully communicate with a server running v1.0.0, ensuring backward
compatibility for security-hardened clients.

v0.5.0 security features:
1. Nonce support for replay attack prevention
2. Bearer token authentication
3. Timestamp validation (already existed, but enhanced)
4. Extensions field for custom security data

Test scenarios:
1. v0.5.0 client with nonce → v1.0.0 server accepts
2. v0.5.0 client with auth → v1.0.0 server authenticates
3. v0.5.0 client with nonce + auth → v1.0.0 server processes both
4. v0.5.0 extensions are preserved in responses
5. Security validation errors are backward compatible
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

import pytest
from starlette.testclient import TestClient

from asap.models.entities import AuthScheme, Capability, Endpoint, Manifest, Skill
from asap.models.enums import TaskStatus
from asap.models.envelope import Envelope
from asap.models.payloads import TaskResponse
from asap.transport.handlers import HandlerRegistry
from asap.transport.server import create_app

if TYPE_CHECKING:
    from collections.abc import Generator


# Note: Rate limiting is automatically disabled for all tests in this package
# via the autouse fixture in conftest.py (following testing-standards.mdc)


# Constants for protocol version simulation
V0_5_0_ASAP_VERSION = "0.5"
V1_0_0_ASAP_VERSION = "1.0"
JSONRPC_VERSION = "2.0"
ASAP_METHOD = "asap.send"


class V050Client:
    """Simulated v0.5.0 client that creates messages with security features.

    This class mimics how a v0.5.0 client would construct messages,
    including security features like nonce, authentication, and extensions.
    v0.5.0 is the production version with security hardening.
    """

    def __init__(self, agent_urn: str) -> None:
        """Initialize the v0.5.0 client.

        Args:
            agent_urn: The URN identifying this client agent
        """
        self.agent_urn = agent_urn
        self._request_counter = 0

    def _next_request_id(self) -> str:
        """Generate next request ID.

        Returns:
            Unique request identifier
        """
        self._request_counter += 1
        return f"v050-req-{self._request_counter}"

    def _generate_nonce(self) -> str:
        """Generate a unique nonce for replay attack prevention.

        Returns:
            Unique nonce string
        """
        return f"nonce-{uuid.uuid4().hex}"

    def create_task_request(
        self,
        recipient: str,
        conversation_id: str,
        skill_id: str,
        input_data: dict[str, Any],
        config: dict[str, Any] | None = None,
        include_nonce: bool = False,
        nonce: str | None = None,
        extensions: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Create a TaskRequest in JSON-RPC format (v0.5.0 style with security).

        v0.5.0 format characteristics:
        - asap_version: "0.5"
        - Optional nonce in extensions for replay protection
        - Full extensions support for custom data
        - Timestamp included (auto-generated by server if not provided)

        Args:
            recipient: Target agent URN
            conversation_id: Conversation identifier
            skill_id: Skill to execute
            input_data: Input data for the skill
            config: Optional configuration
            include_nonce: Whether to include a nonce for replay protection
            nonce: Explicit nonce value (generated if include_nonce=True and nonce=None)
            extensions: Additional extensions to include

        Returns:
            Dictionary representing JSON-RPC wrapped v0.5.0 envelope
        """
        envelope: dict[str, Any] = {
            "asap_version": V0_5_0_ASAP_VERSION,
            "sender": self.agent_urn,
            "recipient": recipient,
            "payload_type": "task.request",
            "payload": {
                "conversation_id": conversation_id,
                "skill_id": skill_id,
                "input": input_data,
            },
        }

        if config:
            envelope["payload"]["config"] = config

        # Build extensions with optional nonce
        ext: dict[str, Any] = {}
        if include_nonce:
            ext["nonce"] = nonce if nonce else self._generate_nonce()
        if extensions:
            ext.update(extensions)
        if ext:
            envelope["extensions"] = ext

        return {
            "jsonrpc": JSONRPC_VERSION,
            "method": ASAP_METHOD,
            "params": {"envelope": envelope},
            "id": self._next_request_id(),
        }

    def create_task_request_with_timestamp(
        self,
        recipient: str,
        conversation_id: str,
        skill_id: str,
        input_data: dict[str, Any],
        timestamp: datetime,
        include_nonce: bool = False,
    ) -> dict[str, Any]:
        """Create a TaskRequest with explicit timestamp.

        Args:
            recipient: Target agent URN
            conversation_id: Conversation identifier
            skill_id: Skill to execute
            input_data: Input data for the skill
            timestamp: Explicit timestamp for the envelope
            include_nonce: Whether to include a nonce

        Returns:
            Dictionary representing JSON-RPC wrapped v0.5.0 envelope with timestamp
        """
        request = self.create_task_request(
            recipient, conversation_id, skill_id, input_data, include_nonce=include_nonce
        )
        request["params"]["envelope"]["timestamp"] = timestamp.isoformat()
        return request

    def create_task_cancel_with_nonce(
        self,
        recipient: str,
        task_id: str,
        reason: str | None = None,
    ) -> dict[str, Any]:
        """Create a TaskCancel with nonce (v0.5.0 security style).

        Args:
            recipient: Target agent URN
            task_id: Task to cancel
            reason: Optional cancellation reason

        Returns:
            Dictionary representing JSON-RPC wrapped v0.5.0 TaskCancel envelope
        """
        payload: dict[str, Any] = {"task_id": task_id}
        if reason:
            payload["reason"] = reason

        envelope = {
            "asap_version": V0_5_0_ASAP_VERSION,
            "sender": self.agent_urn,
            "recipient": recipient,
            "payload_type": "task.cancel",
            "payload": payload,
            "extensions": {"nonce": self._generate_nonce()},
        }

        return {
            "jsonrpc": JSONRPC_VERSION,
            "method": ASAP_METHOD,
            "params": {"envelope": envelope},
            "id": self._next_request_id(),
        }

    def create_request_with_trace_id(
        self,
        recipient: str,
        conversation_id: str,
        skill_id: str,
        input_data: dict[str, Any],
        trace_id: str,
        include_nonce: bool = True,
    ) -> dict[str, Any]:
        """Create a TaskRequest with trace_id for distributed tracing.

        Args:
            recipient: Target agent URN
            conversation_id: Conversation identifier
            skill_id: Skill to execute
            input_data: Input data for the skill
            trace_id: Distributed trace identifier
            include_nonce: Whether to include a nonce

        Returns:
            Dictionary representing JSON-RPC request with trace_id
        """
        request = self.create_task_request(
            recipient, conversation_id, skill_id, input_data, include_nonce=include_nonce
        )
        request["params"]["envelope"]["trace_id"] = trace_id
        return request


def create_v1_server_with_nonce() -> tuple[Manifest, HandlerRegistry, TestClient]:
    """Create a v1.0.0 server with nonce validation for testing.

    Returns:
        Tuple of (manifest, registry, test_client)
    """
    manifest = Manifest(
        id="urn:asap:agent:v1-secure-server",
        name="v1.0.0 Secure Server",
        version="1.0.0",
        description="Test server running v1.0.0 with nonce validation",
        capabilities=Capability(
            asap_version=V1_0_0_ASAP_VERSION,
            skills=[
                Skill(id="echo", description="Echo skill"),
                Skill(id="secure", description="Secure processing skill"),
            ],
            state_persistence=True,
        ),
        endpoints=Endpoint(asap="http://127.0.0.1:8100/asap"),
    )

    registry = HandlerRegistry()

    async def echo_handler(envelope: Envelope, manifest: Manifest) -> Envelope:
        """Handle task requests by echoing input as result."""
        _ = manifest
        payload = envelope.payload_dict
        task_id = f"task_{payload.get('conversation_id', 'unknown')}"

        response_payload = TaskResponse(
            task_id=task_id,
            status=TaskStatus.COMPLETED,
            result={"echo": payload.get("input", {}), "version": "1.0.0"},
            metrics={"duration_ms": 10},
        )

        return Envelope(
            asap_version=V1_0_0_ASAP_VERSION,
            sender=str(envelope.recipient),
            recipient=str(envelope.sender),
            payload_type="task.response",
            payload=response_payload.model_dump(),
            correlation_id=envelope.id,
            trace_id=envelope.trace_id,
        )

    async def cancel_handler(envelope: Envelope, manifest: Manifest) -> Envelope:
        """Handle task cancellation requests."""
        _ = manifest
        payload = envelope.payload_dict
        task_id = payload.get("task_id", "unknown")

        response_payload = TaskResponse(
            task_id=task_id,
            status=TaskStatus.CANCELLED,
            result={"cancelled": True, "reason": payload.get("reason")},
        )

        return Envelope(
            asap_version=V1_0_0_ASAP_VERSION,
            sender=str(envelope.recipient),
            recipient=str(envelope.sender),
            payload_type="task.response",
            payload=response_payload.model_dump(),
            correlation_id=envelope.id,
        )

    registry.register("task.request", echo_handler)
    registry.register("task.cancel", cancel_handler)

    # Create app with nonce validation enabled
    app = create_app(manifest, registry, rate_limit="100000/minute", require_nonce=True)
    client = TestClient(app)

    return manifest, registry, client


def create_v1_server_with_auth() -> tuple[Manifest, HandlerRegistry, TestClient]:
    """Create a v1.0.0 server with authentication for testing.

    Returns:
        Tuple of (manifest, registry, test_client)
    """

    # Token validator that accepts v0.5.0 client tokens
    def token_validator(token: str) -> str | None:
        """Validate Bearer tokens and return agent ID."""
        valid_tokens = {
            "v050-client-token": "urn:asap:agent:v050-client",
            "v050-admin-token": "urn:asap:agent:v050-admin",
        }
        return valid_tokens.get(token)

    manifest = Manifest(
        id="urn:asap:agent:v1-auth-server",
        name="v1.0.0 Auth Server",
        version="1.0.0",
        description="Test server with authentication",
        capabilities=Capability(
            asap_version=V1_0_0_ASAP_VERSION,
            skills=[Skill(id="echo", description="Echo skill")],
            state_persistence=False,
        ),
        endpoints=Endpoint(asap="http://127.0.0.1:8101/asap"),
        auth=AuthScheme(schemes=["bearer"]),
    )

    registry = HandlerRegistry()

    async def echo_handler(envelope: Envelope, manifest: Manifest) -> Envelope:
        """Handle task requests by echoing input as result."""
        _ = manifest
        payload = envelope.payload_dict
        task_id = f"task_{payload.get('conversation_id', 'unknown')}"

        response_payload = TaskResponse(
            task_id=task_id,
            status=TaskStatus.COMPLETED,
            result={"echo": payload.get("input", {}), "authenticated": True},
        )

        return Envelope(
            asap_version=V1_0_0_ASAP_VERSION,
            sender=str(envelope.recipient),
            recipient=str(envelope.sender),
            payload_type="task.response",
            payload=response_payload.model_dump(),
            correlation_id=envelope.id,
        )

    registry.register("task.request", echo_handler)

    app = create_app(
        manifest,
        registry,
        token_validator=token_validator,
        rate_limit="100000/minute",
    )
    client = TestClient(app)

    return manifest, registry, client


@pytest.fixture
def v1_server_with_nonce() -> Generator[TestClient, None, None]:
    """Fixture providing a v1.0.0 server with nonce validation.

    Yields:
        TestClient for the v1.0.0 server
    """
    _, _, client = create_v1_server_with_nonce()
    yield client


@pytest.fixture
def v1_server_with_auth() -> Generator[TestClient, None, None]:
    """Fixture providing a v1.0.0 server with authentication.

    Yields:
        TestClient for the v1.0.0 server
    """
    _, _, client = create_v1_server_with_auth()
    yield client


@pytest.fixture
def v050_client() -> V050Client:
    """Fixture providing a v0.5.0 client.

    Returns:
        V050Client instance
    """
    return V050Client("urn:asap:agent:v050-client")


class TestV050NonceToV10Server:
    """Tests for v0.5.0 nonce compatibility with v1.0.0 server."""

    def test_request_with_nonce_accepted(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that v0.5.0 request with nonce is accepted by v1.0.0 server."""
        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_nonce_001",
            skill_id="echo",
            input_data={"message": "hello with nonce"},
            include_nonce=True,
        )

        response = v1_server_with_nonce.post("/asap", json=request)

        assert response.status_code == 200
        data = response.json()
        assert "result" in data
        envelope = data["result"]["envelope"]
        assert envelope["payload"]["status"] == "completed"
        assert envelope["payload"]["result"]["echo"]["message"] == "hello with nonce"

    def test_duplicate_nonce_rejected(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that duplicate nonce is rejected (replay attack prevention)."""
        # Use explicit nonce to simulate replay attack
        explicit_nonce = "replay-attack-nonce-001"

        request1 = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_replay_001",
            skill_id="echo",
            input_data={"message": "first request"},
            include_nonce=True,
            nonce=explicit_nonce,
        )

        # First request should succeed
        response1 = v1_server_with_nonce.post("/asap", json=request1)
        assert response1.status_code == 200
        assert "result" in response1.json()

        # Second request with same nonce should fail
        request2 = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_replay_002",
            skill_id="echo",
            input_data={"message": "replay attempt"},
            include_nonce=True,
            nonce=explicit_nonce,
        )

        response2 = v1_server_with_nonce.post("/asap", json=request2)
        assert response2.status_code == 200
        data = response2.json()
        assert "error" in data
        assert "nonce" in data["error"]["data"]["error"].lower()

    def test_cancel_with_nonce_accepted(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that TaskCancel with nonce is accepted."""
        request = v050_client.create_task_cancel_with_nonce(
            recipient="urn:asap:agent:v1-secure-server",
            task_id="task_to_cancel_v050",
            reason="User requested via v0.5.0 client",
        )

        response = v1_server_with_nonce.post("/asap", json=request)

        assert response.status_code == 200
        data = response.json()
        assert "result" in data
        envelope = data["result"]["envelope"]
        assert envelope["payload"]["status"] == "cancelled"


class TestV050AuthToV10Server:
    """Tests for v0.5.0 authentication compatibility with v1.0.0 server."""

    def test_bearer_token_accepted(
        self, v1_server_with_auth: TestClient, v050_client: V050Client
    ) -> None:
        """Test that v0.5.0 client with Bearer token is authenticated."""
        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-auth-server",
            conversation_id="conv_v050_auth_001",
            skill_id="echo",
            input_data={"message": "authenticated request"},
        )

        response = v1_server_with_auth.post(
            "/asap",
            json=request,
            headers={"Authorization": "Bearer v050-client-token"},
        )

        assert response.status_code == 200
        data = response.json()
        assert "result" in data
        envelope = data["result"]["envelope"]
        assert envelope["payload"]["status"] == "completed"
        assert envelope["payload"]["result"]["authenticated"] is True

    def test_missing_token_rejected(
        self, v1_server_with_auth: TestClient, v050_client: V050Client
    ) -> None:
        """Test that request without token is rejected."""
        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-auth-server",
            conversation_id="conv_v050_noauth_001",
            skill_id="echo",
            input_data={"message": "no auth"},
        )

        response = v1_server_with_auth.post("/asap", json=request)

        assert response.status_code == 200
        data = response.json()
        assert "error" in data

    def test_invalid_token_rejected(
        self, v1_server_with_auth: TestClient, v050_client: V050Client
    ) -> None:
        """Test that invalid token is rejected."""
        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-auth-server",
            conversation_id="conv_v050_badauth_001",
            skill_id="echo",
            input_data={"message": "bad auth"},
        )

        response = v1_server_with_auth.post(
            "/asap",
            json=request,
            headers={"Authorization": "Bearer invalid-token"},
        )

        assert response.status_code == 200
        data = response.json()
        assert "error" in data


class TestV050ExtensionsCompatibility:
    """Tests for v0.5.0 extensions compatibility with v1.0.0 server."""

    def test_custom_extensions_accepted(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that v0.5.0 custom extensions are accepted by v1.0.0."""
        custom_extensions = {
            "client_version": "0.5.0",
            "client_features": ["nonce", "trace"],
            "custom_metadata": {"env": "test"},
        }

        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_ext_001",
            skill_id="echo",
            input_data={"message": "with extensions"},
            include_nonce=True,
            extensions=custom_extensions,
        )

        response = v1_server_with_nonce.post("/asap", json=request)

        assert response.status_code == 200
        data = response.json()
        assert "result" in data
        assert data["result"]["envelope"]["payload"]["status"] == "completed"

    def test_trace_id_preserved_in_response(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that trace_id from v0.5.0 request is preserved in response."""
        trace_id = "v050-trace-001-abcd1234"

        request = v050_client.create_request_with_trace_id(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_trace_001",
            skill_id="echo",
            input_data={"message": "traced request"},
            trace_id=trace_id,
            include_nonce=True,
        )

        response = v1_server_with_nonce.post("/asap", json=request)

        assert response.status_code == 200
        data = response.json()
        envelope = data["result"]["envelope"]
        # v1.0.0 server should preserve trace_id in response
        assert envelope.get("trace_id") == trace_id

    def test_extensions_with_nonce_only(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that extensions with only nonce field works correctly."""
        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_nonce_only_001",
            skill_id="echo",
            input_data={"message": "nonce only"},
            include_nonce=True,
        )

        # Verify extensions only contains nonce
        assert "extensions" in request["params"]["envelope"]
        assert "nonce" in request["params"]["envelope"]["extensions"]

        response = v1_server_with_nonce.post("/asap", json=request)

        assert response.status_code == 200
        assert "result" in response.json()


class TestV050TimestampCompatibility:
    """Tests for v0.5.0 timestamp validation compatibility with v1.0.0 server."""

    def test_current_timestamp_accepted(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that current timestamp from v0.5.0 client is accepted."""
        now = datetime.now(timezone.utc)

        request = v050_client.create_task_request_with_timestamp(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_ts_001",
            skill_id="echo",
            input_data={"message": "with timestamp"},
            timestamp=now,
            include_nonce=True,
        )

        response = v1_server_with_nonce.post("/asap", json=request)

        assert response.status_code == 200
        data = response.json()
        assert "result" in data

    def test_version_string_accepted(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that "0.5" version string is accepted by v1.0.0 server."""
        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_version_test",
            skill_id="echo",
            input_data={"version_test": True},
            include_nonce=True,
        )

        # Verify envelope uses v0.5.0 version
        assert request["params"]["envelope"]["asap_version"] == "0.5"

        response = v1_server_with_nonce.post("/asap", json=request)

        assert response.status_code == 200


class TestV050ManifestDiscovery:
    """Tests for manifest discovery by v0.5.0 client."""

    def test_manifest_accessible(self, v1_server_with_nonce: TestClient) -> None:
        """Test that v0.5.0 client can discover v1.0.0 server manifest."""
        response = v1_server_with_nonce.get("/.well-known/asap/manifest.json")

        assert response.status_code == 200
        data = response.json()

        # v0.5.0 expected manifest fields
        assert "id" in data
        assert "name" in data
        assert "version" in data
        assert "capabilities" in data
        assert "endpoints" in data

    def test_manifest_shows_v1_version(self, v1_server_with_nonce: TestClient) -> None:
        """Test that manifest shows v1.0.0 capabilities."""
        response = v1_server_with_nonce.get("/.well-known/asap/manifest.json")
        data = response.json()

        # Server advertises v1.0.0 capabilities
        capabilities = data["capabilities"]
        assert capabilities["asap_version"] == V1_0_0_ASAP_VERSION


class TestV050ErrorHandlingCompatibility:
    """Tests for error handling compatibility between v0.5.0 client and v1.0.0 server."""

    def test_validation_error_format_readable(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that validation errors are in v0.5.0-readable format."""
        # Send malformed JSON-RPC (missing method)
        request = {
            "jsonrpc": "2.0",
            "params": {
                "envelope": {
                    "asap_version": "0.5",
                    "sender": v050_client.agent_urn,
                    "recipient": "urn:asap:agent:v1-secure-server",
                    "payload_type": "task.request",
                    "payload": {},
                    "extensions": {"nonce": "test-nonce-001"},
                }
            },
            "id": "error-test-1",
        }

        response = v1_server_with_nonce.post("/asap", json=request)

        # JSON-RPC always returns 200, errors are in the body
        assert response.status_code == 200
        data = response.json()

        # Error response should be in JSON-RPC format v0.5.0 expects
        assert "error" in data
        assert "code" in data["error"]
        assert "message" in data["error"]

    def test_nonce_error_format(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that nonce errors are clearly identified."""
        nonce = "duplicate-nonce-test-002"

        # First request
        request1 = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_nonce_error_001",
            skill_id="echo",
            input_data={"test": True},
            include_nonce=True,
            nonce=nonce,
        )
        v1_server_with_nonce.post("/asap", json=request1)

        # Second request with same nonce
        request2 = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_nonce_error_002",
            skill_id="echo",
            input_data={"test": True},
            include_nonce=True,
            nonce=nonce,
        )
        response = v1_server_with_nonce.post("/asap", json=request2)

        data = response.json()
        assert "error" in data
        # Error data should contain nonce information
        assert "nonce" in data["error"]["data"]["error"].lower()


class TestV050CorrelationIdHandling:
    """Tests for correlation ID handling across versions."""

    def test_correlation_id_in_response(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that responses include correlation_id linking to request."""
        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_corr_001",
            skill_id="echo",
            input_data={"track_me": True},
            include_nonce=True,
        )

        # Add explicit envelope ID
        request["params"]["envelope"]["id"] = "v050-envelope-001"

        response = v1_server_with_nonce.post("/asap", json=request)
        data = response.json()

        # Response should have correlation_id matching request envelope id
        envelope = data["result"]["envelope"]
        assert envelope.get("correlation_id") == "v050-envelope-001"

    def test_jsonrpc_id_preserved(
        self, v1_server_with_nonce: TestClient, v050_client: V050Client
    ) -> None:
        """Test that JSON-RPC request id is preserved in response."""
        request = v050_client.create_task_request(
            recipient="urn:asap:agent:v1-secure-server",
            conversation_id="conv_v050_jsonrpc_001",
            skill_id="echo",
            input_data={"test_jsonrpc": True},
            include_nonce=True,
        )

        request_id = request["id"]
        response = v1_server_with_nonce.post("/asap", json=request)
        data = response.json()

        # JSON-RPC response id should match request id
        assert data["id"] == request_id
