#!/usr/bin/env python3
"""Generate TypeScript types from ASAP Protocol JSON Schemas.

This script relies on `export_schemas.py` to first generate the JSON schema
files in `schemas/`, then uses `json-schema-to-typescript` (via npx) to compile
them into a single `protocol.d.ts` file. Duplicate type/interface declarations
are removed (IMP-9 from PR-58 code review).
"""

import re
import subprocess
from pathlib import Path


def _deduplicate_type_aliases(ts_content: str) -> str:
    """Remove duplicate single-line type aliases (e.g. export type TaskId = string), keeping first."""
    seen: set[str] = set()
    result_lines: list[str] = []
    for line in ts_content.splitlines():
        stripped = line.strip()
        # Only deduplicate single-line: export type X = Y;
        type_match = re.match(r"export\s+type\s+(\w+)\s*=", stripped)
        if type_match and stripped.endswith(";"):
            name = type_match.group(1)
            if name in seen:
                continue
            seen.add(name)
        result_lines.append(line)
    return "\n".join(result_lines) + "\n" if result_lines else ""


def main() -> None:
    # 1. Export schemas
    print("🚀 Exporting ASAP Protocol JSON Schemas...")
    subprocess.run(["python3", "scripts/export_schemas.py"], check=True)

    # 2. Combine and convert schemas
    schemas_dir = Path("schemas")
    web_types_dir = Path("apps/web/src/types")
    web_types_dir.mkdir(parents=True, exist_ok=True)
    output_file = web_types_dir / "protocol.d.ts"

    print("\n🚀 Converting JSON Schemas to TypeScript...")

    # We'll use npx json2ts for each generated schema and append to the output
    schema_files = list(schemas_dir.glob("**/*.json"))

    all_output: list[str] = []
    for sf in schema_files:
        print(f"Converting {sf.name}...")
        try:
            cmd = ["npx", "json2ts", "-i", str(sf.absolute()), "--bannerComment", ""]
            result = subprocess.run(
                cmd, capture_output=True, text=True, cwd="apps/web", check=False
            )

            if result.returncode == 0:
                all_output.append(result.stdout)
            else:
                print(f"⚠️ Failed to convert {sf.name}: {result.stderr}")
        except Exception as e:
            print(f"Error converting {sf.name}: {e}")

    combined = "\n".join(all_output)
    deduped = _deduplicate_type_aliases(combined)

    with open(output_file, "w") as out:
        out.write("/**\n * This file was automatically generated by json-schema-to-typescript.\n")
        out.write(
            " * DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models.\n */\n\n"
        )
        out.write(deduped)

    print(f"\n✨ Successfully generated TypeScript types at {output_file}")


if __name__ == "__main__":
    main()
