#!/usr/bin/env python3
"""Generate TypeScript types from ASAP Protocol JSON Schemas.

This script relies on `export_schemas.py` to first generate the JSON schema
files in `schemas/`, then uses `json-schema-to-typescript` (via npx) to compile
them into a single `protocol.d.ts` file.
"""

import subprocess
from pathlib import Path


def main() -> None:
    # 1. Export schemas
    print("🚀 Exporting ASAP Protocol JSON Schemas...")
    subprocess.run(["python3", "scripts/export_schemas.py"], check=True)

    # 2. Combine and convert schemas
    schemas_dir = Path("schemas")
    web_types_dir = Path("apps/web/src/types")
    web_types_dir.mkdir(parents=True, exist_ok=True)
    output_file = web_types_dir / "protocol.d.ts"

    print("\n🚀 Converting JSON Schemas to TypeScript...")

    # We'll use npx json2ts for each generated schema and append to the output
    schema_files = list(schemas_dir.glob("**/*.json"))

    with open(output_file, "w") as out:
        out.write("/* eslint-disable */\n")
        out.write("/**\n * This file was automatically generated by json-schema-to-typescript.\n")
        out.write(
            " * DO NOT MODIFY IT BY HAND. Instead, modify the source Pydantic models.\n */\n\n"
        )

    for sf in schema_files:
        print(f"Converting {sf.name}...")
        try:
            # We run the node module json2ts natively installed in apps/web
            cmd = ["npx", "json2ts", "-i", str(sf.absolute()), "--bannerComment", ""]
            result = subprocess.run(
                cmd, capture_output=True, text=True, cwd="apps/web", check=False
            )

            if result.returncode == 0:
                with open(output_file, "a") as out:
                    out.write(result.stdout + "\n")
            else:
                print(f"⚠️ Failed to convert {sf.name}: {result.stderr}")
        except Exception as e:
            print(f"Error converting {sf.name}: {e}")

    print(f"\n✨ Successfully generated TypeScript types at {output_file}")


if __name__ == "__main__":
    main()
